// Mapper generated by CodeGenerator
package com.example.project.mapper;

import com.example.project.entity.SysConfig;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 *  Mapper接口
 *
 * @author CodeGenerator
 */
@Mapper
public interface SysConfigMapper extends BaseMapper<SysConfig> {
    // 自定义方法可在此添加
}
