// Mapper generated by CodeGenerator
package com.example.project.mapper;

import com.example.project.entity.SysDictItem;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 *  Mapper接口
 *
 * @author CodeGenerator
 */
@Mapper
public interface SysDictItemMapper extends BaseMapper<SysDictItem> {
    // 自定义方法可在此添加
}
