// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysConfig;
import com.example.project.dto.SysConfigQueryDTO;
import com.example.project.mapper.SysConfigMapper;
import com.example.project.service.SysConfigRepository;
import org.springframework.stereotype.Service;

/**
 * SysConfig Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysConfigRepositoryImpl extends ServiceImpl<SysConfigMapper, SysConfig> implements SysConfigRepository {

    @Override
    public PageResult<SysConfig> page(SysConfigQueryDTO queryDTO) {
        LambdaQueryWrapper<SysConfig> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysConfig> page = new Page<>(pageNum, pageSize);

        IPage<SysConfig> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
