// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysDictCategory;
import com.example.project.dto.SysDictCategoryQueryDTO;
import com.example.project.mapper.SysDictCategoryMapper;
import com.example.project.service.SysDictCategoryRepository;
import org.springframework.stereotype.Service;

/**
 * SysDictCategory Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysDictCategoryRepositoryImpl extends ServiceImpl<SysDictCategoryMapper, SysDictCategory> implements SysDictCategoryRepository {

    @Override
    public PageResult<SysDictCategory> page(SysDictCategoryQueryDTO queryDTO) {
        LambdaQueryWrapper<SysDictCategory> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysDictCategory> page = new Page<>(pageNum, pageSize);

        IPage<SysDictCategory> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
