// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysDictItem;
import com.example.project.dto.SysDictItemQueryDTO;
import com.example.project.mapper.SysDictItemMapper;
import com.example.project.service.SysDictItemRepository;
import org.springframework.stereotype.Service;

/**
 * SysDictItem Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysDictItemRepositoryImpl extends ServiceImpl<SysDictItemMapper, SysDictItem> implements SysDictItemRepository {

    @Override
    public PageResult<SysDictItem> page(SysDictItemQueryDTO queryDTO) {
        LambdaQueryWrapper<SysDictItem> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysDictItem> page = new Page<>(pageNum, pageSize);

        IPage<SysDictItem> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
