// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysLoginLog;
import com.example.project.dto.SysLoginLogQueryDTO;
import com.example.project.mapper.SysLoginLogMapper;
import com.example.project.service.SysLoginLogRepository;
import org.springframework.stereotype.Service;

/**
 * SysLoginLog Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysLoginLogRepositoryImpl extends ServiceImpl<SysLoginLogMapper, SysLoginLog> implements SysLoginLogRepository {

    @Override
    public PageResult<SysLoginLog> page(SysLoginLogQueryDTO queryDTO) {
        LambdaQueryWrapper<SysLoginLog> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysLoginLog> page = new Page<>(pageNum, pageSize);

        IPage<SysLoginLog> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
