// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysMenu;
import com.example.project.dto.SysMenuQueryDTO;
import com.example.project.mapper.SysMenuMapper;
import com.example.project.service.SysMenuRepository;
import org.springframework.stereotype.Service;

/**
 * SysMenu Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysMenuRepositoryImpl extends ServiceImpl<SysMenuMapper, SysMenu> implements SysMenuRepository {

    @Override
    public PageResult<SysMenu> page(SysMenuQueryDTO queryDTO) {
        LambdaQueryWrapper<SysMenu> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysMenu> page = new Page<>(pageNum, pageSize);

        IPage<SysMenu> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
