// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysOrg;
import com.example.project.dto.SysOrgQueryDTO;
import com.example.project.mapper.SysOrgMapper;
import com.example.project.service.SysOrgRepository;
import org.springframework.stereotype.Service;

/**
 * SysOrg Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysOrgRepositoryImpl extends ServiceImpl<SysOrgMapper, SysOrg> implements SysOrgRepository {

    @Override
    public PageResult<SysOrg> page(SysOrgQueryDTO queryDTO) {
        LambdaQueryWrapper<SysOrg> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysOrg> page = new Page<>(pageNum, pageSize);

        IPage<SysOrg> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
