// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysPermission;
import com.example.project.dto.SysPermissionQueryDTO;
import com.example.project.mapper.SysPermissionMapper;
import com.example.project.service.SysPermissionRepository;
import org.springframework.stereotype.Service;

/**
 * SysPermission Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysPermissionRepositoryImpl extends ServiceImpl<SysPermissionMapper, SysPermission> implements SysPermissionRepository {

    @Override
    public PageResult<SysPermission> page(SysPermissionQueryDTO queryDTO) {
        LambdaQueryWrapper<SysPermission> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysPermission> page = new Page<>(pageNum, pageSize);

        IPage<SysPermission> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
