// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysRole;
import com.example.project.dto.SysRoleQueryDTO;
import com.example.project.mapper.SysRoleMapper;
import com.example.project.service.SysRoleRepository;
import org.springframework.stereotype.Service;

/**
 * SysRole Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysRoleRepositoryImpl extends ServiceImpl<SysRoleMapper, SysRole> implements SysRoleRepository {

    @Override
    public PageResult<SysRole> page(SysRoleQueryDTO queryDTO) {
        LambdaQueryWrapper<SysRole> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysRole> page = new Page<>(pageNum, pageSize);

        IPage<SysRole> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
