// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysRolePermission;
import com.example.project.dto.SysRolePermissionQueryDTO;
import com.example.project.mapper.SysRolePermissionMapper;
import com.example.project.service.SysRolePermissionRepository;
import org.springframework.stereotype.Service;

/**
 * SysRolePermission Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysRolePermissionRepositoryImpl extends ServiceImpl<SysRolePermissionMapper, SysRolePermission> implements SysRolePermissionRepository {

    @Override
    public PageResult<SysRolePermission> page(SysRolePermissionQueryDTO queryDTO) {
        LambdaQueryWrapper<SysRolePermission> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysRolePermission> page = new Page<>(pageNum, pageSize);

        IPage<SysRolePermission> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
