// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysRoleOrg;
import com.example.project.dto.SysRoleOrgQueryDTO;
import com.example.project.mapper.SysRoleOrgMapper;
import com.example.project.service.SysRoleOrgRepository;
import org.springframework.stereotype.Service;

/**
 * SysRoleOrg Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysRoleOrgRepositoryImpl extends ServiceImpl<SysRoleOrgMapper, SysRoleOrg> implements SysRoleOrgRepository {

    @Override
    public PageResult<SysRoleOrg> page(SysRoleOrgQueryDTO queryDTO) {
        LambdaQueryWrapper<SysRoleOrg> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysRoleOrg> page = new Page<>(pageNum, pageSize);

        IPage<SysRoleOrg> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
