// ServiceImpl generated by CodeGenerator
package com.example.project.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.example.project.common.PageResult;
import com.example.project.entity.SysUserRole;
import com.example.project.dto.SysUserRoleQueryDTO;
import com.example.project.mapper.SysUserRoleMapper;
import com.example.project.service.SysUserRoleRepository;
import org.springframework.stereotype.Service;

/**
 * SysUserRole Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class SysUserRoleRepositoryImpl extends ServiceImpl<SysUserRoleMapper, SysUserRole> implements SysUserRoleRepository {

    @Override
    public PageResult<SysUserRole> page(SysUserRoleQueryDTO queryDTO) {
        LambdaQueryWrapper<SysUserRole> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<SysUserRole> page = new Page<>(pageNum, pageSize);

        IPage<SysUserRole> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
