// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysConfig;
import com.example.project.dto.SysConfigQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysConfig Repository接口
 *
 * @author CodeGenerator
 */
public interface SysConfigRepository extends IService<SysConfig> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysConfig> page(SysConfigQueryDTO queryDTO);
}
