// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysDictItem;
import com.example.project.dto.SysDictItemQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysDictItem Repository接口
 *
 * @author CodeGenerator
 */
public interface SysDictItemRepository extends IService<SysDictItem> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysDictItem> page(SysDictItemQueryDTO queryDTO);
}
