// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysDictCategory;
import com.example.project.dto.SysDictCategoryQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysDictCategory Repository接口
 *
 * @author CodeGenerator
 */
public interface SysDictCategoryRepository extends IService<SysDictCategory> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysDictCategory> page(SysDictCategoryQueryDTO queryDTO);
}
