// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysLoginLog;
import com.example.project.dto.SysLoginLogQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysLoginLog Repository接口
 *
 * @author CodeGenerator
 */
public interface SysLoginLogRepository extends IService<SysLoginLog> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysLoginLog> page(SysLoginLogQueryDTO queryDTO);
}
