// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysMenu;
import com.example.project.dto.SysMenuQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysMenu Repository接口
 *
 * @author CodeGenerator
 */
public interface SysMenuRepository extends IService<SysMenu> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysMenu> page(SysMenuQueryDTO queryDTO);
}
