// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysOrg;
import com.example.project.dto.SysOrgQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysOrg Repository接口
 *
 * @author CodeGenerator
 */
public interface SysOrgRepository extends IService<SysOrg> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysOrg> page(SysOrgQueryDTO queryDTO);
}
