// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysPermission;
import com.example.project.dto.SysPermissionQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysPermission Repository接口
 *
 * @author CodeGenerator
 */
public interface SysPermissionRepository extends IService<SysPermission> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysPermission> page(SysPermissionQueryDTO queryDTO);
}
