// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysRole;
import com.example.project.dto.SysRoleQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysRole Repository接口
 *
 * @author CodeGenerator
 */
public interface SysRoleRepository extends IService<SysRole> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysRole> page(SysRoleQueryDTO queryDTO);
}
