// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysRolePermission;
import com.example.project.dto.SysRolePermissionQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysRolePermission Repository接口
 *
 * @author CodeGenerator
 */
public interface SysRolePermissionRepository extends IService<SysRolePermission> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysRolePermission> page(SysRolePermissionQueryDTO queryDTO);
}
