// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysRoleOrg;
import com.example.project.dto.SysRoleOrgQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysRoleOrg Repository接口
 *
 * @author CodeGenerator
 */
public interface SysRoleOrgRepository extends IService<SysRoleOrg> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysRoleOrg> page(SysRoleOrgQueryDTO queryDTO);
}
