// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysUserRole;
import com.example.project.dto.SysUserRoleQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysUserRole Repository接口
 *
 * @author CodeGenerator
 */
public interface SysUserRoleRepository extends IService<SysUserRole> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysUserRole> page(SysUserRoleQueryDTO queryDTO);
}
