// Service generated by CodeGenerator
package com.example.project.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.example.project.entity.SysUser;
import com.example.project.dto.SysUserQueryDTO;
import com.example.project.common.PageResult;

/**
 * SysUser Repository接口
 *
 * @author CodeGenerator
 */
public interface SysUserRepository extends IService<SysUser> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<SysUser> page(SysUserQueryDTO queryDTO);
}
