// Controller generated by CodeGenerator
package com.example.project.controller;

import com.example.project.common.PageResult;
import com.example.project.common.Result;
import com.example.project.entity.SysConfig;
import com.example.project.dto.SysConfigQueryDTO;
import com.example.project.service.SysConfigRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 *  Controller
 *
 * @author CodeGenerator
 */
@RestController
@RequestMapping("/sysConfig")
@Validated
public class SysConfigController {

    @Autowired
    private SysConfigRepository sysConfigRepository;

    /**
     * 分页查询列表（POST方式，Body传参，支持模糊查询）
     */
    @PostMapping("/list")
    public Result<PageResult<SysConfig>> list(@RequestBody SysConfigQueryDTO sysConfigQueryDTO) {
        PageResult<SysConfig> result = sysConfigRepository.page(sysConfigQueryDTO);
        return Result.success(result);
    }

    /**
     * 查询单条记录（GET方式，URL参数）
     */
    @GetMapping("/get")
    public Result<SysConfig> get(@RequestParam("variable") String variable) {
        SysConfig record = sysConfigRepository.getById(variable);
        if (record == null) {
            return Result.fail("记录不存在");
        }
        return Result.success(record);
    }

    /**
     * 新增记录（POST方式，Body传参）
     */
    @PostMapping("/save")
    public Result<String> save(@RequestBody SysConfig sysConfig) {
        boolean success = sysConfigRepository.save(sysConfig);
        return success ? Result.success("新增成功") : Result.fail("新增失败");
    }

    /**
     * 更新记录（POST方式，Body传参）
     */
    @PostMapping("/update")
    public Result<String> update(@RequestBody SysConfig sysConfig) {
        boolean success = sysConfigRepository.updateById(sysConfig);
        return success ? Result.success("更新成功") : Result.fail("更新失败");
    }

    /**
     * 删除记录（GET方式，URL参数）
     */
    @GetMapping("/delete")
    public Result<String> delete(@RequestParam("variable") String variable) {
        boolean success = sysConfigRepository.removeById(variable);
        return success ? Result.success("删除成功") : Result.fail("删除失败");
    }

    /**
     * 批量删除（POST方式，Body传参）
     */
    @PostMapping("/batchDelete")
    public Result<String> batchDelete(@RequestBody List<String> ids) {
        if (ids == null || ids.isEmpty()) {
            return Result.fail("ID列表不能为空");
        }
        for (String id : ids) {
            sysConfigRepository.removeById(id);
        }
        return Result.success("批量删除成功");
    }
}
