// Controller generated by CodeGenerator
package com.example.project.controller;

import com.example.project.common.PageResult;
import com.example.project.common.Result;
import com.example.project.entity.SysLoginLog;
import com.example.project.dto.SysLoginLogQueryDTO;
import com.example.project.service.SysLoginLogRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 *  Controller
 *
 * @author CodeGenerator
 */
@RestController
@RequestMapping("/sysLoginLog")
@Validated
public class SysLoginLogController {

    @Autowired
    private SysLoginLogRepository sysLoginLogRepository;

    /**
     * 分页查询列表（POST方式，Body传参，支持模糊查询）
     */
    @PostMapping("/list")
    public Result<PageResult<SysLoginLog>> list(@RequestBody SysLoginLogQueryDTO sysLoginLogQueryDTO) {
        PageResult<SysLoginLog> result = sysLoginLogRepository.page(sysLoginLogQueryDTO);
        return Result.success(result);
    }

    /**
     * 查询单条记录（GET方式，URL参数）
     */
    @GetMapping("/get")
    public Result<SysLoginLog> get(@RequestParam("id") Long id) {
        SysLoginLog record = sysLoginLogRepository.getById(id);
        if (record == null) {
            return Result.fail("记录不存在");
        }
        return Result.success(record);
    }

    /**
     * 新增记录（POST方式，Body传参）
     */
    @PostMapping("/save")
    public Result<String> save(@RequestBody SysLoginLog sysLoginLog) {
        boolean success = sysLoginLogRepository.save(sysLoginLog);
        return success ? Result.success("新增成功") : Result.fail("新增失败");
    }

    /**
     * 更新记录（POST方式，Body传参）
     */
    @PostMapping("/update")
    public Result<String> update(@RequestBody SysLoginLog sysLoginLog) {
        boolean success = sysLoginLogRepository.updateById(sysLoginLog);
        return success ? Result.success("更新成功") : Result.fail("更新失败");
    }

    /**
     * 删除记录（GET方式，URL参数）
     */
    @GetMapping("/delete")
    public Result<String> delete(@RequestParam("id") Long id) {
        boolean success = sysLoginLogRepository.removeById(id);
        return success ? Result.success("删除成功") : Result.fail("删除失败");
    }

    /**
     * 批量删除（POST方式，Body传参）
     */
    @PostMapping("/batchDelete")
    public Result<String> batchDelete(@RequestBody List<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return Result.fail("ID列表不能为空");
        }
        for (Long id : ids) {
            sysLoginLogRepository.removeById(id);
        }
        return Result.success("批量删除成功");
    }
}
