// Controller generated by CodeGenerator
package com.example.project.controller;

import com.example.project.common.PageResult;
import com.example.project.common.Result;
import com.example.project.entity.SysPermission;
import com.example.project.dto.SysPermissionQueryDTO;
import com.example.project.service.SysPermissionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 *  Controller
 *
 * @author CodeGenerator
 */
@RestController
@RequestMapping("/sysPermission")
@Validated
public class SysPermissionController {

    @Autowired
    private SysPermissionRepository sysPermissionRepository;

    /**
     * 分页查询列表（POST方式，Body传参，支持模糊查询）
     */
    @PostMapping("/list")
    public Result<PageResult<SysPermission>> list(@RequestBody SysPermissionQueryDTO sysPermissionQueryDTO) {
        PageResult<SysPermission> result = sysPermissionRepository.page(sysPermissionQueryDTO);
        return Result.success(result);
    }

    /**
     * 查询单条记录（GET方式，URL参数）
     */
    @GetMapping("/get")
    public Result<SysPermission> get(@RequestParam("id") Long id) {
        SysPermission record = sysPermissionRepository.getById(id);
        if (record == null) {
            return Result.fail("记录不存在");
        }
        return Result.success(record);
    }

    /**
     * 新增记录（POST方式，Body传参）
     */
    @PostMapping("/save")
    public Result<String> save(@RequestBody SysPermission sysPermission) {
        boolean success = sysPermissionRepository.save(sysPermission);
        return success ? Result.success("新增成功") : Result.fail("新增失败");
    }

    /**
     * 更新记录（POST方式，Body传参）
     */
    @PostMapping("/update")
    public Result<String> update(@RequestBody SysPermission sysPermission) {
        boolean success = sysPermissionRepository.updateById(sysPermission);
        return success ? Result.success("更新成功") : Result.fail("更新失败");
    }

    /**
     * 删除记录（GET方式，URL参数）
     */
    @GetMapping("/delete")
    public Result<String> delete(@RequestParam("id") Long id) {
        boolean success = sysPermissionRepository.removeById(id);
        return success ? Result.success("删除成功") : Result.fail("删除失败");
    }

    /**
     * 批量删除（POST方式，Body传参）
     */
    @PostMapping("/batchDelete")
    public Result<String> batchDelete(@RequestBody List<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return Result.fail("ID列表不能为空");
        }
        for (Long id : ids) {
            sysPermissionRepository.removeById(id);
        }
        return Result.success("批量删除成功");
    }
}
