// Controller generated by CodeGenerator
package com.example.project.controller;

import com.example.project.common.PageResult;
import com.example.project.common.Result;
import com.example.project.entity.SysRolePermission;
import com.example.project.dto.SysRolePermissionQueryDTO;
import com.example.project.service.SysRolePermissionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 *  Controller
 *
 * @author CodeGenerator
 */
@RestController
@RequestMapping("/sysRolePermission")
@Validated
public class SysRolePermissionController {

    @Autowired
    private SysRolePermissionRepository sysRolePermissionRepository;

    /**
     * 分页查询列表（POST方式，Body传参，支持模糊查询）
     */
    @PostMapping("/list")
    public Result<PageResult<SysRolePermission>> list(@RequestBody SysRolePermissionQueryDTO sysRolePermissionQueryDTO) {
        PageResult<SysRolePermission> result = sysRolePermissionRepository.page(sysRolePermissionQueryDTO);
        return Result.success(result);
    }

    /**
     * 查询单条记录（GET方式，URL参数）
     */
    @GetMapping("/get")
    public Result<SysRolePermission> get(@RequestParam("role_id") Long role_id) {
        SysRolePermission record = sysRolePermissionRepository.getById(role_id);
        if (record == null) {
            return Result.fail("记录不存在");
        }
        return Result.success(record);
    }

    /**
     * 新增记录（POST方式，Body传参）
     */
    @PostMapping("/save")
    public Result<String> save(@RequestBody SysRolePermission sysRolePermission) {
        boolean success = sysRolePermissionRepository.save(sysRolePermission);
        return success ? Result.success("新增成功") : Result.fail("新增失败");
    }

    /**
     * 更新记录（POST方式，Body传参）
     */
    @PostMapping("/update")
    public Result<String> update(@RequestBody SysRolePermission sysRolePermission) {
        boolean success = sysRolePermissionRepository.updateById(sysRolePermission);
        return success ? Result.success("更新成功") : Result.fail("更新失败");
    }

    /**
     * 删除记录（GET方式，URL参数）
     */
    @GetMapping("/delete")
    public Result<String> delete(@RequestParam("role_id") Long role_id) {
        boolean success = sysRolePermissionRepository.removeById(role_id);
        return success ? Result.success("删除成功") : Result.fail("删除失败");
    }

    /**
     * 批量删除（POST方式，Body传参）
     */
    @PostMapping("/batchDelete")
    public Result<String> batchDelete(@RequestBody List<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return Result.fail("ID列表不能为空");
        }
        for (Long id : ids) {
            sysRolePermissionRepository.removeById(id);
        }
        return Result.success("批量删除成功");
    }
}
