// Controller generated by CodeGenerator
package com.example.project.controller;

import com.example.project.common.PageResult;
import com.example.project.common.Result;
import com.example.project.entity.SysRoleOrg;
import com.example.project.dto.SysRoleOrgQueryDTO;
import com.example.project.service.SysRoleOrgRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 *  Controller
 *
 * @author CodeGenerator
 */
@RestController
@RequestMapping("/sysRoleOrg")
@Validated
public class SysRoleOrgController {

    @Autowired
    private SysRoleOrgRepository sysRoleOrgRepository;

    /**
     * 分页查询列表（POST方式，Body传参，支持模糊查询）
     */
    @PostMapping("/list")
    public Result<PageResult<SysRoleOrg>> list(@RequestBody SysRoleOrgQueryDTO sysRoleOrgQueryDTO) {
        PageResult<SysRoleOrg> result = sysRoleOrgRepository.page(sysRoleOrgQueryDTO);
        return Result.success(result);
    }

    /**
     * 查询单条记录（GET方式，URL参数）
     */
    @GetMapping("/get")
    public Result<SysRoleOrg> get(@RequestParam("id") Long id) {
        SysRoleOrg record = sysRoleOrgRepository.getById(id);
        if (record == null) {
            return Result.fail("记录不存在");
        }
        return Result.success(record);
    }

    /**
     * 新增记录（POST方式，Body传参）
     */
    @PostMapping("/save")
    public Result<String> save(@RequestBody SysRoleOrg sysRoleOrg) {
        boolean success = sysRoleOrgRepository.save(sysRoleOrg);
        return success ? Result.success("新增成功") : Result.fail("新增失败");
    }

    /**
     * 更新记录（POST方式，Body传参）
     */
    @PostMapping("/update")
    public Result<String> update(@RequestBody SysRoleOrg sysRoleOrg) {
        boolean success = sysRoleOrgRepository.updateById(sysRoleOrg);
        return success ? Result.success("更新成功") : Result.fail("更新失败");
    }

    /**
     * 删除记录（GET方式，URL参数）
     */
    @GetMapping("/delete")
    public Result<String> delete(@RequestParam("id") Long id) {
        boolean success = sysRoleOrgRepository.removeById(id);
        return success ? Result.success("删除成功") : Result.fail("删除失败");
    }

    /**
     * 批量删除（POST方式，Body传参）
     */
    @PostMapping("/batchDelete")
    public Result<String> batchDelete(@RequestBody List<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return Result.fail("ID列表不能为空");
        }
        for (Long id : ids) {
            sysRoleOrgRepository.removeById(id);
        }
        return Result.success("批量删除成功");
    }
}
