// CodeGenerator.java - Mybatis Plus pagination version
// All String.format templates verified: placeholders == arguments

package com.example.codegen.generator;

import com.example.codegen.config.CodeGeneratorConfig;
import com.example.codegen.model.ColumnInfo;
import com.example.codegen.model.TableInfo;
import com.example.codegen.util.DbUtil;
import com.example.codegen.util.StringUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.util.List;

/**
 * 代码生成器主类
 * 根据数据库表自动生成 Controller、Service、ServiceImpl、Dao、Mapper XML
 *
 * @author CodeGenerator
 */
public class CodeGenerator {

    private static final Logger log = LoggerFactory.getLogger(CodeGenerator.class);

    private final CodeGeneratorConfig config;

    public CodeGenerator(CodeGeneratorConfig config) {
        this.config = config;
    }

    /**
     * 执行代码生成（支持单表、批量）
     */
    public void generate() {
        Connection connection = null;
        try {
            connection = DbUtil.getConnection(config);
            log.info("数据库连接成功");

            // 获取所有表
            List<String> allTables = DbUtil.getTables(connection);
            log.info("数据库中共 {} 张表", allTables.size());

            // 解析要生成的表
            List<String> targetTables = config.resolveTableNames(allTables);

            if (targetTables.isEmpty()) {
                log.warn("未指定要生成的表，请设置 tableName / tablePrefix / tables 配置");
                log.info("可用表列表：{}", allTables);
                return;
            }

            log.info("将生成 {} 张表的代码: {}", targetTables.size(), targetTables);

            // 逐表生成
            for (String tableName : targetTables) {
                generateForTable(connection, tableName);
            }

            log.info("代码生成完成！共生成 {} 个模块", targetTables.size());

        } catch (Exception e) {
            log.error("代码生成失败", e);
            throw new RuntimeException("代码生成失败: " + e.getMessage(), e);
        } finally {
            DbUtil.closeConnection(connection);
        }
    }

    /**
     * 为单张表生成代码
     */
    private void generateForTable(Connection connection, String tableName) throws Exception {
        log.info("========== 开始生成表: {} ==========", tableName);

        TableInfo tableInfo = DbUtil.getTableInfo(connection, tableName);
        List<ColumnInfo> columns = DbUtil.getColumns(connection, tableName);
        tableInfo.setColumns(columns);

        log.info("表信息: {}", tableInfo);

        generateEntity(tableInfo);
        generateController(tableInfo);
        generateQueryDto(tableInfo);
        generateService(tableInfo);
        generateServiceImpl(tableInfo);
        generateDao(tableInfo);
        generateMapperXml(tableInfo);

        log.info("========== 表 {} 生成完成 ==========", tableName);
    }

    /**
      * 生成实体类
      */
    private void generateEntity(TableInfo tableInfo) throws IOException {
        String entityName = tableInfo.getEntityName();
        String pkType = getPrimaryKeyType(tableInfo);

        long pkCount = tableInfo.getColumns().stream().filter(ColumnInfo::isPrimaryKey).count();
        boolean isCompositeKey = pkCount > 1;
        boolean isStringPk = "String".equals(pkType);

        StringBuilder fields = new StringBuilder();
        for (ColumnInfo col : tableInfo.getColumns()) {
            String propertyName = StringUtil.toCamelCase(col.getColumnName());
            fields.append("\n    /**\n");
            fields.append("     * ").append(col.getColumnComment().isEmpty() ? propertyName : col.getColumnComment()).append("\n");
            fields.append("     */\n");
            if (col.isPrimaryKey() && !isCompositeKey) {
                if (isStringPk) {
                    fields.append("    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.ASSIGN_ID)\n");
                } else {
                    fields.append("    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)\n");
                }
            }
            fields.append("    private ").append(col.getJavaType()).append(" ").append(propertyName).append(";\n");
        }

        String content = String.format("""
// Entity generated by CodeGenerator
package %1$s.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * %2$s
 *
 * @author CodeGenerator
 */
@Data
@TableName("%3$s")
public class %4$s {%5$s}

""",
                config.getBasePackage(),
                tableInfo.getComment().isEmpty() ? entityName : tableInfo.getComment(),
                tableInfo.getTableName(),
                entityName,
                fields.toString()
        );

        saveToFile("entity", entityName + ".java", content);
    }

    /**
     * 生成 Controller（使用Mybatis Plus分页）
     * 模板占位符数: 43
     */
    private void generateController(TableInfo tableInfo) throws IOException {
        String entityName = tableInfo.getEntityName();
        String lowerEntityName = StringUtil.firstCharToLower(entityName);
        String queryDtoName = entityName + "QueryDTO";
        String lowerQueryDtoName = StringUtil.firstCharToLower(queryDtoName);
        String pkCol = getPrimaryKeyColumn(tableInfo);
        String pkType = getPrimaryKeyType(tableInfo);

        String content = String.format("""
// Controller generated by CodeGenerator
package %1$s.controller;

import %1$s.common.PageResult;
import %1$s.common.Result;
import %1$s.entity.%2$s;
import %1$s.dto.%3$s;
import %1$s.service.%2$sRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * %4$s Controller
 *
 * @author CodeGenerator
 */
@RestController
@RequestMapping("/%5$s")
@Validated
public class %6$sController {

    @Autowired
    private %2$sRepository %7$sRepository;

    /**
     * 分页查询列表（POST方式，Body传参，支持模糊查询）
     */
    @PostMapping("/list")
    public Result<PageResult<%2$s>> list(@RequestBody %3$s %8$s) {
        PageResult<%2$s> result = %7$sRepository.page(%8$s);
        return Result.success(result);
    }

    /**
     * 查询单条记录（GET方式，URL参数）
     */
    @GetMapping("/get")
    public Result<%2$s> get(@RequestParam("%9$s") %10$s %9$s) {
        %2$s record = %7$sRepository.getById(%9$s);
        if (record == null) {
            return Result.fail("记录不存在");
        }
        return Result.success(record);
    }

    /**
     * 新增记录（POST方式，Body传参）
     */
    @PostMapping("/save")
    public Result<String> save(@RequestBody %2$s %7$s) {
        boolean success = %7$sRepository.save(%7$s);
        return success ? Result.success("新增成功") : Result.fail("新增失败");
    }

    /**
     * 更新记录（POST方式，Body传参）
     */
    @PostMapping("/update")
    public Result<String> update(@RequestBody %2$s %7$s) {
        boolean success = %7$sRepository.updateById(%7$s);
        return success ? Result.success("更新成功") : Result.fail("更新失败");
    }

    /**
     * 删除记录（GET方式，URL参数）
     */
    @GetMapping("/delete")
    public Result<String> delete(@RequestParam("%9$s") %10$s %9$s) {
        boolean success = %7$sRepository.removeById(%9$s);
        return success ? Result.success("删除成功") : Result.fail("删除失败");
    }

    /**
     * 批量删除（POST方式，Body传参）
     */
    @PostMapping("/batchDelete")
    public Result<String> batchDelete(@RequestBody List<%10$s> ids) {
        if (ids == null || ids.isEmpty()) {
            return Result.fail("ID列表不能为空");
        }
        for (%10$s id : ids) {
            %7$sRepository.removeById(id);
        }
        return Result.success("批量删除成功");
    }
}
""",
                config.getBasePackage(),
                entityName,
                queryDtoName,
                tableInfo.getComment(),
                lowerEntityName,
                entityName,
                lowerEntityName,
                lowerQueryDtoName,
                pkCol,
                pkType
        );

        saveToFile("controller", entityName + "Controller.java", content);
    }

    /**
     * 生成查询条件DTO
     */
    private void generateQueryDto(TableInfo tableInfo) throws IOException {
        String entityName = tableInfo.getEntityName();
        String queryDtoName = entityName + "QueryDTO";
        String basePackage = config.getBasePackage();

        StringBuilder fields = new StringBuilder();
        StringBuilder equalsConditions = new StringBuilder();
        StringBuilder likeConditions = new StringBuilder();
        for (ColumnInfo col : tableInfo.getColumns()) {
            String propertyName = StringUtil.toCamelCase(col.getColumnName());
            String getterName = StringUtil.toPascalCase(col.getColumnName());
            fields.append("    /**\n");
            fields.append("     * ").append(col.getColumnComment().isEmpty() ? propertyName : col.getColumnComment()).append("\n");
            fields.append("     */\n");
            fields.append("    private ").append(col.getJavaType()).append(" ").append(propertyName).append(";\n\n");

            if (!"String".equals(col.getJavaType())) {
                equalsConditions.append("        wrapper.eq(this.").append(propertyName).append(" != null, ").append(entityName).append("::get").append(getterName).append(", this.").append(propertyName).append(");\n");
            } else {
                likeConditions.append("        wrapper.like(StringUtil.isNotEmpty(this.").append(propertyName).append("), ").append(entityName).append("::get").append(getterName).append(", this.").append(propertyName).append(");\n");
            }
        }

        String imports = String.format("""
// QueryDTO generated by CodeGenerator
package %s.dto;

import %s.entity.%s;
import %s.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;

""", basePackage, basePackage, entityName, basePackage);

        String template = String.format("""

/**
 * %s 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class %s {

%s    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<%s> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<%s> wrapper) {
%s        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<%s> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<%s> wrapper) {
%s        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<%s> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<%s> wrapper) {
%s        return wrapper;
    }
}
""",
                tableInfo.getComment().isEmpty() ? entityName : tableInfo.getComment(),
                queryDtoName,
                fields.toString(),
                entityName,
                entityName,
                equalsConditions.toString(),
                entityName,
                entityName,
                likeConditions.toString(),
                entityName,
                entityName,
                equalsConditions.toString() + likeConditions.toString()
        );

        saveToFile("dto", queryDtoName + ".java", imports + template);
    }

    /**
     * 生成 Service 接口（MyBatis Plus IService 风格）
     */
    private void generateService(TableInfo tableInfo) throws IOException {
        String entityName = tableInfo.getEntityName();
        String mapperName = entityName + "Mapper";
        String queryDtoName = entityName + "QueryDTO";

        String content = String.format("""
// Service generated by CodeGenerator
package %1$s.service;

import com.baomidou.mybatisplus.extension.service.IService;
import %1$s.entity.%2$s;
import %1$s.dto.%3$s;
import %1$s.common.PageResult;

/**
 * %4$s Repository接口
 *
 * @author CodeGenerator
 */
public interface %2$sRepository extends IService<%2$s> {

    /**
     * 分页查询（支持 QueryDTO 条件）
     */
    PageResult<%2$s> page(%3$s queryDTO);
}
""",
                config.getBasePackage(),
                entityName,
                queryDtoName,
                tableInfo.getComment().isEmpty() ? entityName : tableInfo.getComment()
        );

        saveToFile("service", entityName + "Repository.java", content);
    }

    /**
     * 生成 ServiceImpl（MyBatis Plus ServiceImpl 风格）
     */
    private void generateServiceImpl(TableInfo tableInfo) throws IOException {
        String entityName = tableInfo.getEntityName();
        String lowerEntityName = StringUtil.firstCharToLower(entityName);
        String mapperName = entityName + "Mapper";
        String queryDtoName = entityName + "QueryDTO";
        String pkType = getPrimaryKeyType(tableInfo);
        String pkGetter = "get" + StringUtil.toPascalCase(getPrimaryKeyColumn(tableInfo));

        String content = String.format("""
// ServiceImpl generated by CodeGenerator
package %1$s.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import %1$s.common.PageResult;
import %1$s.entity.%2$s;
import %1$s.dto.%3$s;
import %1$s.mapper.%4$s;
import %1$s.service.%2$sRepository;
import org.springframework.stereotype.Service;

/**
 * %5$s Repository实现
 *
 * @author CodeGenerator
 */
@Service
public class %2$sRepositoryImpl extends ServiceImpl<%4$s, %2$s> implements %2$sRepository {

    @Override
    public PageResult<%2$s> page(%3$s queryDTO) {
        LambdaQueryWrapper<%2$s> wrapper = new LambdaQueryWrapper<>();
        queryDTO.buildEqualsConditions(wrapper);
        queryDTO.buildLikeConditions(wrapper);

        int pageNum = queryDTO.getPageNum() != null ? queryDTO.getPageNum() : 1;
        int pageSize = queryDTO.getPageSize() != null ? queryDTO.getPageSize() : 10;
        Page<%2$s> page = new Page<>(pageNum, pageSize);

        IPage<%2$s> result = baseMapper.selectPage(page, wrapper);

        return new PageResult<>(
                result.getRecords(),
                result.getTotal(),
                (int) result.getCurrent(),
                (int) result.getSize()
        );
    }

}
""",
                config.getBasePackage(),
                entityName,
                queryDtoName,
                mapperName,
                tableInfo.getComment().isEmpty() ? entityName : tableInfo.getComment(),
                pkType,
                pkGetter
        );

        saveToFile("service/impl", entityName + "RepositoryImpl.java", content);
    }

    /**
     * 生成 Mapper 接口
     * 模板占位符数: 7
     */
    private void generateDao(TableInfo tableInfo) throws IOException {
        String entityName = tableInfo.getEntityName();
        String mapperName = entityName + "Mapper";

        String content = String.format("""
// Mapper generated by CodeGenerator
package %1$s.mapper;

import %1$s.entity.%2$s;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * %3$s Mapper接口
 *
 * @author CodeGenerator
 */
@Mapper
public interface %4$s extends BaseMapper<%2$s> {
    // 自定义方法可在此添加
}
""",
                config.getBasePackage(),
                entityName,
                tableInfo.getComment(),
                mapperName
        );

        saveToFile("mapper", mapperName + ".java", content);
    }

    /**
     * 生成 Mapper XML
     * 模板占位符数: 15
     */
    private void generateMapperXml(TableInfo tableInfo) throws IOException {
        String entityName = tableInfo.getEntityName();
        String mapperName = entityName + "Mapper";
        String resultMapId = entityName + "Map";

        StringBuilder columns = new StringBuilder();
        for (ColumnInfo col : tableInfo.getColumns()) {
            if (col.isPrimaryKey()) {
                continue;
            }
            columns.append("        <result column=\"").append(col.getColumnName())
                    .append("\" property=\"").append(StringUtil.toCamelCase(col.getColumnName()))
                    .append("\" />\n");
        }

        String content = String.format("""
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<!-- Mapper XML generated by CodeGenerator -->
<!-- BaseMapper 已提供：selectList / selectById / insert / updateById / deleteById / deleteBatchIds -->
<mapper namespace="%s.mapper.%s">

    <!-- 结果集映射（用于自定义复杂查询） -->
    <resultMap id="%s" type="%s.entity.%s">
        <id column="%s" property="%s" />
%s    </resultMap>

    <!-- 基础列片段（自定义SQL中可引用） -->
    <sql id="Base_Column_List">
        %s
    </sql>

</mapper>
""",
                config.getBasePackage(), mapperName,
                resultMapId, config.getBasePackage(), entityName,
                getPrimaryKeyColumn(tableInfo), StringUtil.toCamelCase(getPrimaryKeyColumn(tableInfo)),
                columns.toString(),
                String.join(", ", tableInfo.getColumns().stream().map(ColumnInfo::getColumnName).toArray(String[]::new))
        );

        saveToFile("mapper", mapperName + ".xml", content);
    }

    // ========== 辅助方法 ==========

    private String getPrimaryKeyColumn(TableInfo tableInfo) {
        return tableInfo.getColumns().stream()
                .filter(ColumnInfo::isPrimaryKey)
                .findFirst()
                .map(ColumnInfo::getColumnName)
                .orElse(tableInfo.getColumns().get(0).getColumnName());
    }

    private String getPrimaryKeyType(TableInfo tableInfo) {
        return tableInfo.getColumns().stream()
                .filter(ColumnInfo::isPrimaryKey)
                .findFirst()
                .map(col -> col.getJavaType())
                .orElse("Long");
    }

    private void saveToFile(String dir, String fileName, String content) throws IOException {
        String outputPath = config.getOutputPath();
        String packagePath = config.getBasePackage().replace(".", File.separator);
        String fullDir = outputPath + File.separator + packagePath + File.separator + dir;
        String fullPath = fullDir + File.separator + fileName;

        File directory = new File(fullDir);
        if (!directory.exists()) {
            directory.mkdirs();
        }

        try (java.io.OutputStreamWriter writer = new java.io.OutputStreamWriter(
                new java.io.FileOutputStream(fullPath), java.nio.charset.StandardCharsets.UTF_8)) {
            writer.write(content);
        }

        log.info("  生成文件: {}", fullPath);
    }
}
