// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysConfig;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysConfig 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysConfigQueryDTO {

    /**
     * variable
     */
    private String variable;

    /**
     * value
     */
    private String value;

    /**
     * setTime
     */
    private LocalDateTime setTime;

    /**
     * setBy
     */
    private String setBy;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysConfig> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysConfig> wrapper) {
        wrapper.eq(this.setTime != null, SysConfig::getSetTime, this.setTime);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysConfig> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysConfig> wrapper) {
        wrapper.like(StringUtil.isNotEmpty(this.variable), SysConfig::getVariable, this.variable);
        wrapper.like(StringUtil.isNotEmpty(this.value), SysConfig::getValue, this.value);
        wrapper.like(StringUtil.isNotEmpty(this.setBy), SysConfig::getSetBy, this.setBy);
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysConfig> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysConfig> wrapper) {
        wrapper.eq(this.setTime != null, SysConfig::getSetTime, this.setTime);
        wrapper.like(StringUtil.isNotEmpty(this.variable), SysConfig::getVariable, this.variable);
        wrapper.like(StringUtil.isNotEmpty(this.value), SysConfig::getValue, this.value);
        wrapper.like(StringUtil.isNotEmpty(this.setBy), SysConfig::getSetBy, this.setBy);
        return wrapper;
    }
}
