// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysDictCategory;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysDictCategory 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysDictCategoryQueryDTO {

    /**
     * id
     */
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * description
     */
    private String description;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * name
     */
    private String name;

    /**
     * sort
     */
    private Integer sort;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictCategory> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictCategory> wrapper) {
        wrapper.eq(this.id != null, SysDictCategory::getId, this.id);
        wrapper.eq(this.enabled != null, SysDictCategory::getEnabled, this.enabled);
        wrapper.eq(this.sort != null, SysDictCategory::getSort, this.sort);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictCategory> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictCategory> wrapper) {
        wrapper.like(StringUtil.isNotEmpty(this.code), SysDictCategory::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.description), SysDictCategory::getDescription, this.description);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysDictCategory::getName, this.name);
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictCategory> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictCategory> wrapper) {
        wrapper.eq(this.id != null, SysDictCategory::getId, this.id);
        wrapper.eq(this.enabled != null, SysDictCategory::getEnabled, this.enabled);
        wrapper.eq(this.sort != null, SysDictCategory::getSort, this.sort);
        wrapper.like(StringUtil.isNotEmpty(this.code), SysDictCategory::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.description), SysDictCategory::getDescription, this.description);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysDictCategory::getName, this.name);
        return wrapper;
    }
}
