// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysDictItem;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysDictItem 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysDictItemQueryDTO {

    /**
     * id
     */
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * name
     */
    private String name;

    /**
     * remark
     */
    private String remark;

    /**
     * sort
     */
    private Integer sort;

    /**
     * itemValue
     */
    private String itemValue;

    /**
     * categoryId
     */
    private Long categoryId;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictItem> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictItem> wrapper) {
        wrapper.eq(this.id != null, SysDictItem::getId, this.id);
        wrapper.eq(this.enabled != null, SysDictItem::getEnabled, this.enabled);
        wrapper.eq(this.sort != null, SysDictItem::getSort, this.sort);
        wrapper.eq(this.categoryId != null, SysDictItem::getCategoryId, this.categoryId);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictItem> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictItem> wrapper) {
        wrapper.like(StringUtil.isNotEmpty(this.code), SysDictItem::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysDictItem::getName, this.name);
        wrapper.like(StringUtil.isNotEmpty(this.remark), SysDictItem::getRemark, this.remark);
        wrapper.like(StringUtil.isNotEmpty(this.itemValue), SysDictItem::getItemValue, this.itemValue);
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictItem> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysDictItem> wrapper) {
        wrapper.eq(this.id != null, SysDictItem::getId, this.id);
        wrapper.eq(this.enabled != null, SysDictItem::getEnabled, this.enabled);
        wrapper.eq(this.sort != null, SysDictItem::getSort, this.sort);
        wrapper.eq(this.categoryId != null, SysDictItem::getCategoryId, this.categoryId);
        wrapper.like(StringUtil.isNotEmpty(this.code), SysDictItem::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysDictItem::getName, this.name);
        wrapper.like(StringUtil.isNotEmpty(this.remark), SysDictItem::getRemark, this.remark);
        wrapper.like(StringUtil.isNotEmpty(this.itemValue), SysDictItem::getItemValue, this.itemValue);
        return wrapper;
    }
}
