// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysLoginLog;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysLoginLog 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysLoginLogQueryDTO {

    /**
     * id
     */
    private Long id;

    /**
     * device
     */
    private String device;

    /**
     * ip
     */
    private String ip;

    /**
     * message
     */
    private String message;

    /**
     * success
     */
    private Boolean success;

    /**
     * time
     */
    private LocalDateTime time;

    /**
     * username
     */
    private String username;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysLoginLog> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysLoginLog> wrapper) {
        wrapper.eq(this.id != null, SysLoginLog::getId, this.id);
        wrapper.eq(this.success != null, SysLoginLog::getSuccess, this.success);
        wrapper.eq(this.time != null, SysLoginLog::getTime, this.time);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysLoginLog> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysLoginLog> wrapper) {
        wrapper.like(StringUtil.isNotEmpty(this.device), SysLoginLog::getDevice, this.device);
        wrapper.like(StringUtil.isNotEmpty(this.ip), SysLoginLog::getIp, this.ip);
        wrapper.like(StringUtil.isNotEmpty(this.message), SysLoginLog::getMessage, this.message);
        wrapper.like(StringUtil.isNotEmpty(this.username), SysLoginLog::getUsername, this.username);
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysLoginLog> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysLoginLog> wrapper) {
        wrapper.eq(this.id != null, SysLoginLog::getId, this.id);
        wrapper.eq(this.success != null, SysLoginLog::getSuccess, this.success);
        wrapper.eq(this.time != null, SysLoginLog::getTime, this.time);
        wrapper.like(StringUtil.isNotEmpty(this.device), SysLoginLog::getDevice, this.device);
        wrapper.like(StringUtil.isNotEmpty(this.ip), SysLoginLog::getIp, this.ip);
        wrapper.like(StringUtil.isNotEmpty(this.message), SysLoginLog::getMessage, this.message);
        wrapper.like(StringUtil.isNotEmpty(this.username), SysLoginLog::getUsername, this.username);
        return wrapper;
    }
}
