// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysMenu;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysMenu 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysMenuQueryDTO {

    /**
     * id
     */
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * icon
     */
    private String icon;

    /**
     * name
     */
    private String name;

    /**
     * parentId
     */
    private Long parentId;

    /**
     * path
     */
    private String path;

    /**
     * permissionCode
     */
    private String permissionCode;

    /**
     * sort
     */
    private Integer sort;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysMenu> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysMenu> wrapper) {
        wrapper.eq(this.id != null, SysMenu::getId, this.id);
        wrapper.eq(this.enabled != null, SysMenu::getEnabled, this.enabled);
        wrapper.eq(this.parentId != null, SysMenu::getParentId, this.parentId);
        wrapper.eq(this.sort != null, SysMenu::getSort, this.sort);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysMenu> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysMenu> wrapper) {
        wrapper.like(StringUtil.isNotEmpty(this.code), SysMenu::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.icon), SysMenu::getIcon, this.icon);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysMenu::getName, this.name);
        wrapper.like(StringUtil.isNotEmpty(this.path), SysMenu::getPath, this.path);
        wrapper.like(StringUtil.isNotEmpty(this.permissionCode), SysMenu::getPermissionCode, this.permissionCode);
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysMenu> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysMenu> wrapper) {
        wrapper.eq(this.id != null, SysMenu::getId, this.id);
        wrapper.eq(this.enabled != null, SysMenu::getEnabled, this.enabled);
        wrapper.eq(this.parentId != null, SysMenu::getParentId, this.parentId);
        wrapper.eq(this.sort != null, SysMenu::getSort, this.sort);
        wrapper.like(StringUtil.isNotEmpty(this.code), SysMenu::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.icon), SysMenu::getIcon, this.icon);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysMenu::getName, this.name);
        wrapper.like(StringUtil.isNotEmpty(this.path), SysMenu::getPath, this.path);
        wrapper.like(StringUtil.isNotEmpty(this.permissionCode), SysMenu::getPermissionCode, this.permissionCode);
        return wrapper;
    }
}
