// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysOrg;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysOrg 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysOrgQueryDTO {

    /**
     * id
     */
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * description
     */
    private String description;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * manager
     */
    private String manager;

    /**
     * name
     */
    private String name;

    /**
     * parentId
     */
    private Long parentId;

    /**
     * sort
     */
    private Integer sort;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysOrg> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysOrg> wrapper) {
        wrapper.eq(this.id != null, SysOrg::getId, this.id);
        wrapper.eq(this.enabled != null, SysOrg::getEnabled, this.enabled);
        wrapper.eq(this.parentId != null, SysOrg::getParentId, this.parentId);
        wrapper.eq(this.sort != null, SysOrg::getSort, this.sort);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysOrg> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysOrg> wrapper) {
        wrapper.like(StringUtil.isNotEmpty(this.code), SysOrg::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.description), SysOrg::getDescription, this.description);
        wrapper.like(StringUtil.isNotEmpty(this.manager), SysOrg::getManager, this.manager);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysOrg::getName, this.name);
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysOrg> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysOrg> wrapper) {
        wrapper.eq(this.id != null, SysOrg::getId, this.id);
        wrapper.eq(this.enabled != null, SysOrg::getEnabled, this.enabled);
        wrapper.eq(this.parentId != null, SysOrg::getParentId, this.parentId);
        wrapper.eq(this.sort != null, SysOrg::getSort, this.sort);
        wrapper.like(StringUtil.isNotEmpty(this.code), SysOrg::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.description), SysOrg::getDescription, this.description);
        wrapper.like(StringUtil.isNotEmpty(this.manager), SysOrg::getManager, this.manager);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysOrg::getName, this.name);
        return wrapper;
    }
}
