// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysPermission;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysPermission 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysPermissionQueryDTO {

    /**
     * id
     */
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * name
     */
    private String name;

    /**
     * type
     */
    private String type;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysPermission> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysPermission> wrapper) {
        wrapper.eq(this.id != null, SysPermission::getId, this.id);
        wrapper.eq(this.enabled != null, SysPermission::getEnabled, this.enabled);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysPermission> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysPermission> wrapper) {
        wrapper.like(StringUtil.isNotEmpty(this.code), SysPermission::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysPermission::getName, this.name);
        wrapper.like(StringUtil.isNotEmpty(this.type), SysPermission::getType, this.type);
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysPermission> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysPermission> wrapper) {
        wrapper.eq(this.id != null, SysPermission::getId, this.id);
        wrapper.eq(this.enabled != null, SysPermission::getEnabled, this.enabled);
        wrapper.like(StringUtil.isNotEmpty(this.code), SysPermission::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysPermission::getName, this.name);
        wrapper.like(StringUtil.isNotEmpty(this.type), SysPermission::getType, this.type);
        return wrapper;
    }
}
