// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysRolePermission;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysRolePermission 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysRolePermissionQueryDTO {

    /**
     * roleId
     */
    private Long roleId;

    /**
     * permissionId
     */
    private Long permissionId;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRolePermission> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRolePermission> wrapper) {
        wrapper.eq(this.roleId != null, SysRolePermission::getRoleId, this.roleId);
        wrapper.eq(this.permissionId != null, SysRolePermission::getPermissionId, this.permissionId);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRolePermission> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRolePermission> wrapper) {
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRolePermission> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRolePermission> wrapper) {
        wrapper.eq(this.roleId != null, SysRolePermission::getRoleId, this.roleId);
        wrapper.eq(this.permissionId != null, SysRolePermission::getPermissionId, this.permissionId);
        return wrapper;
    }
}
