// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysRole;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysRole 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysRoleQueryDTO {

    /**
     * id
     */
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * dataScope
     */
    private String dataScope;

    /**
     * description
     */
    private String description;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * name
     */
    private String name;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRole> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRole> wrapper) {
        wrapper.eq(this.id != null, SysRole::getId, this.id);
        wrapper.eq(this.enabled != null, SysRole::getEnabled, this.enabled);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRole> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRole> wrapper) {
        wrapper.like(StringUtil.isNotEmpty(this.code), SysRole::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.dataScope), SysRole::getDataScope, this.dataScope);
        wrapper.like(StringUtil.isNotEmpty(this.description), SysRole::getDescription, this.description);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysRole::getName, this.name);
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRole> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRole> wrapper) {
        wrapper.eq(this.id != null, SysRole::getId, this.id);
        wrapper.eq(this.enabled != null, SysRole::getEnabled, this.enabled);
        wrapper.like(StringUtil.isNotEmpty(this.code), SysRole::getCode, this.code);
        wrapper.like(StringUtil.isNotEmpty(this.dataScope), SysRole::getDataScope, this.dataScope);
        wrapper.like(StringUtil.isNotEmpty(this.description), SysRole::getDescription, this.description);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysRole::getName, this.name);
        return wrapper;
    }
}
