// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysRoleOrg;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysRoleOrg 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysRoleOrgQueryDTO {

    /**
     * id
     */
    private Long id;

    /**
     * orgId
     */
    private Long orgId;

    /**
     * roleId
     */
    private Long roleId;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRoleOrg> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRoleOrg> wrapper) {
        wrapper.eq(this.id != null, SysRoleOrg::getId, this.id);
        wrapper.eq(this.orgId != null, SysRoleOrg::getOrgId, this.orgId);
        wrapper.eq(this.roleId != null, SysRoleOrg::getRoleId, this.roleId);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRoleOrg> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRoleOrg> wrapper) {
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRoleOrg> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysRoleOrg> wrapper) {
        wrapper.eq(this.id != null, SysRoleOrg::getId, this.id);
        wrapper.eq(this.orgId != null, SysRoleOrg::getOrgId, this.orgId);
        wrapper.eq(this.roleId != null, SysRoleOrg::getRoleId, this.roleId);
        return wrapper;
    }
}
