// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysUser;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysUser 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysUserQueryDTO {

    /**
     * id
     */
    private Long id;

    /**
     * createdAt
     */
    private LocalDateTime createdAt;

    /**
     * email
     */
    private String email;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * name
     */
    private String name;

    /**
     * orgId
     */
    private Long orgId;

    /**
     * passwordHash
     */
    private String passwordHash;

    /**
     * phone
     */
    private String phone;

    /**
     * updatedAt
     */
    private LocalDateTime updatedAt;

    /**
     * username
     */
    private String username;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUser> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUser> wrapper) {
        wrapper.eq(this.id != null, SysUser::getId, this.id);
        wrapper.eq(this.createdAt != null, SysUser::getCreatedAt, this.createdAt);
        wrapper.eq(this.enabled != null, SysUser::getEnabled, this.enabled);
        wrapper.eq(this.orgId != null, SysUser::getOrgId, this.orgId);
        wrapper.eq(this.updatedAt != null, SysUser::getUpdatedAt, this.updatedAt);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUser> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUser> wrapper) {
        wrapper.like(StringUtil.isNotEmpty(this.email), SysUser::getEmail, this.email);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysUser::getName, this.name);
        wrapper.like(StringUtil.isNotEmpty(this.passwordHash), SysUser::getPasswordHash, this.passwordHash);
        wrapper.like(StringUtil.isNotEmpty(this.phone), SysUser::getPhone, this.phone);
        wrapper.like(StringUtil.isNotEmpty(this.username), SysUser::getUsername, this.username);
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUser> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUser> wrapper) {
        wrapper.eq(this.id != null, SysUser::getId, this.id);
        wrapper.eq(this.createdAt != null, SysUser::getCreatedAt, this.createdAt);
        wrapper.eq(this.enabled != null, SysUser::getEnabled, this.enabled);
        wrapper.eq(this.orgId != null, SysUser::getOrgId, this.orgId);
        wrapper.eq(this.updatedAt != null, SysUser::getUpdatedAt, this.updatedAt);
        wrapper.like(StringUtil.isNotEmpty(this.email), SysUser::getEmail, this.email);
        wrapper.like(StringUtil.isNotEmpty(this.name), SysUser::getName, this.name);
        wrapper.like(StringUtil.isNotEmpty(this.passwordHash), SysUser::getPasswordHash, this.passwordHash);
        wrapper.like(StringUtil.isNotEmpty(this.phone), SysUser::getPhone, this.phone);
        wrapper.like(StringUtil.isNotEmpty(this.username), SysUser::getUsername, this.username);
        return wrapper;
    }
}
