// QueryDTO generated by CodeGenerator
package com.example.project.dto;

import com.example.project.entity.SysUserRole;
import com.example.project.util.StringUtil;
import lombok.Data;
import java.time.LocalDateTime;


/**
 * SysUserRole 查询条件DTO
 *
 * @author CodeGenerator
 */
@Data
public class SysUserRoleQueryDTO {

    /**
     * userId
     */
    private Long userId;

    /**
     * roleId
     */
    private Long roleId;

    // ==================== 分页参数 ====================
    /**
     * 页码
     */
    private Integer pageNum = 1;

    /**
     * 每页条数
     */
    private Integer pageSize = 10;

    // ==================== 查询条件方法 ====================

    /**
     * 构建精确查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUserRole> buildEqualsConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUserRole> wrapper) {
        wrapper.eq(this.userId != null, SysUserRole::getUserId, this.userId);
        wrapper.eq(this.roleId != null, SysUserRole::getRoleId, this.roleId);
        return wrapper;
    }

    /**
     * 构建模糊查询条件
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUserRole> buildLikeConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUserRole> wrapper) {
        return wrapper;
    }

    /**
     * 构建完整查询条件（精确+模糊）
     */
    public com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUserRole> buildQueryConditions(
            com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper<SysUserRole> wrapper) {
        wrapper.eq(this.userId != null, SysUserRole::getUserId, this.userId);
        wrapper.eq(this.roleId != null, SysUserRole::getRoleId, this.roleId);
        return wrapper;
    }
}
