// Entity generated by CodeGenerator
package com.example.project.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * SysConfig
 *
 * @author CodeGenerator
 */
@Data
@TableName("sys_config")
public class SysConfig {
    /**
     * variable
     */
    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.ASSIGN_ID)
    private String variable;

    /**
     * value
     */
    private String value;

    /**
     * setTime
     */
    private LocalDateTime setTime;

    /**
     * setBy
     */
    private String setBy;
}

