// Entity generated by CodeGenerator
package com.example.project.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * SysDictItem
 *
 * @author CodeGenerator
 */
@Data
@TableName("sys_dict_item")
public class SysDictItem {
    /**
     * id
     */
    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * name
     */
    private String name;

    /**
     * remark
     */
    private String remark;

    /**
     * sort
     */
    private Integer sort;

    /**
     * itemValue
     */
    private String itemValue;

    /**
     * categoryId
     */
    private Long categoryId;
}

