// Entity generated by CodeGenerator
package com.example.project.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * SysLoginLog
 *
 * @author CodeGenerator
 */
@Data
@TableName("sys_login_log")
public class SysLoginLog {
    /**
     * id
     */
    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)
    private Long id;

    /**
     * device
     */
    private String device;

    /**
     * ip
     */
    private String ip;

    /**
     * message
     */
    private String message;

    /**
     * success
     */
    private Boolean success;

    /**
     * time
     */
    private LocalDateTime time;

    /**
     * username
     */
    private String username;
}

