// Entity generated by CodeGenerator
package com.example.project.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * SysMenu
 *
 * @author CodeGenerator
 */
@Data
@TableName("sys_menu")
public class SysMenu {
    /**
     * id
     */
    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * icon
     */
    private String icon;

    /**
     * name
     */
    private String name;

    /**
     * parentId
     */
    private Long parentId;

    /**
     * path
     */
    private String path;

    /**
     * permissionCode
     */
    private String permissionCode;

    /**
     * sort
     */
    private Integer sort;
}

