// Entity generated by CodeGenerator
package com.example.project.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * SysOrg
 *
 * @author CodeGenerator
 */
@Data
@TableName("sys_org")
public class SysOrg {
    /**
     * id
     */
    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * description
     */
    private String description;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * manager
     */
    private String manager;

    /**
     * name
     */
    private String name;

    /**
     * parentId
     */
    private Long parentId;

    /**
     * sort
     */
    private Integer sort;
}

