// Entity generated by CodeGenerator
package com.example.project.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * SysPermission
 *
 * @author CodeGenerator
 */
@Data
@TableName("sys_permission")
public class SysPermission {
    /**
     * id
     */
    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * name
     */
    private String name;

    /**
     * type
     */
    private String type;
}

