// Entity generated by CodeGenerator
package com.example.project.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * SysRole
 *
 * @author CodeGenerator
 */
@Data
@TableName("sys_role")
public class SysRole {
    /**
     * id
     */
    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)
    private Long id;

    /**
     * code
     */
    private String code;

    /**
     * dataScope
     */
    private String dataScope;

    /**
     * description
     */
    private String description;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * name
     */
    private String name;
}

