// Entity generated by CodeGenerator
package com.example.project.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * SysRoleOrg
 *
 * @author CodeGenerator
 */
@Data
@TableName("sys_role_org")
public class SysRoleOrg {
    /**
     * id
     */
    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)
    private Long id;

    /**
     * orgId
     */
    private Long orgId;

    /**
     * roleId
     */
    private Long roleId;
}

