// Entity generated by CodeGenerator
package com.example.project.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * SysUser
 *
 * @author CodeGenerator
 */
@Data
@TableName("sys_user")
public class SysUser {
    /**
     * id
     */
    @TableId(type = com.baomidou.mybatisplus.annotation.IdType.AUTO)
    private Long id;

    /**
     * createdAt
     */
    private LocalDateTime createdAt;

    /**
     * email
     */
    private String email;

    /**
     * enabled
     */
    private Boolean enabled;

    /**
     * name
     */
    private String name;

    /**
     * orgId
     */
    private Long orgId;

    /**
     * passwordHash
     */
    private String passwordHash;

    /**
     * phone
     */
    private String phone;

    /**
     * updatedAt
     */
    private LocalDateTime updatedAt;

    /**
     * username
     */
    private String username;
}

